package com.example.ServerlessAws.encapsulaciones;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;

@DynamoDBTable(tableName="reservas")
public class Reserva {
    @DynamoDBHashKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "idEstudiante")
    private String idEstudiante;
    @DynamoDBAttribute(attributeName = "nombre")
    private String nombre;
    @DynamoDBAttribute(attributeName = "carrera")
    private String carrera;
    @DynamoDBAttribute(attributeName = "laboratorio")
    private String laboratorio;
    @DynamoDBAttribute(attributeName = "fecha")
    private String fecha;

    public Reserva() {
    }

    public Reserva(String idEstudiante, String nombre, String carrera, String laboratorio, String fecha) {
        this.idEstudiante = idEstudiante;
        this.nombre = nombre;
        this.carrera = carrera;
        this.laboratorio = laboratorio;
        this.fecha = fecha;
    }

    public Reserva(String idEstudiante, String nombre, String laboratorio, String fecha) {
        this.idEstudiante = idEstudiante;
        this.nombre = nombre;
        this.laboratorio = laboratorio;
        this.fecha = fecha;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getIdEstudiante() {
        return idEstudiante;
    }

    public void setIdEstudiante(String idEstudiante) {
        this.idEstudiante = idEstudiante;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getLaboratorio() {
        return laboratorio;
    }

    public void setLaboratorio(String laboratorio) {
        this.laboratorio = laboratorio;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getCarrera() {
        return carrera;
    }

    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
}
